from bs4 import BeautifulSoup
import requests
import re
import os
import os.path as osp
import csv


def filename2url(filename):
    """Coverts filename (with no extension) to google search url"""
    search_terms = filename.replace('_', ' ').replace('-', ' ').replace(' ', '+')
    return 'https://www.google.com/search?q=' + search_terms + '+lyrics'


def find_google_play_url(url):
    """Finds google play url in google search of song. Returns None if nothing found"""
    soup = create_soup(url)
    google_play_url = None
    for link in soup.find_all('a', href=True):
        if link['href'].startswith('https://play.google.com/music'):
            google_play_url = link['href']
            break
    return google_play_url


def create_soup(url):
    response = requests.get(url)
    return BeautifulSoup(response.content, 'lxml')


def visible(element):
    """Check if html element is visible"""
    if element.parent.name in ['style', 'script', '[document]', 'head', 'title']:
        return False
    elif re.match('<!--.*-->', str(element.encode('utf-8'))):
        return False
    return True


def generate_csv(dict_of_lists, filename):
    """Make csv file from dict of lists. Each row is the key followed by the list elements"""
    with open(filename, 'w') as file:
        writer = csv.writer(file)
        for key in dict_of_lists:
            writer.writerow([key] + dict_of_lists[key])


def read_csv(filename):
    """Reads csv generated by generate_csv(). Returns dict of sets"""
    lyric_dict = {}
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            lyric_dict[row[0]] = set(row[1:])
    return lyric_dict


def make_lyric_file(dirpath):
    """Finds lyrics for each acapella in dirpath. Outputs to csv file."""
    files = [f for f in os.listdir(dirpath) if osp.isfile(osp.join(dirpath, f))]
    lyric_dict = {}
    for file in files:
        name = osp.splitext(file)[0]
        google_search_url = filename2url(name)
        google_play_url = find_google_play_url(google_search_url)

        if google_play_url:
            text = create_soup(google_play_url).find_all(text=True)
            visible_text = list(filter(visible, text))
            lyrics = visible_text[visible_text.index('Lyrics') + 1:]

            lyric_set = set()
            for line in lyrics:
                words = line.split()
                for word in words:
                    clean_word = re.sub(r'[\W]+', '', word.lower())
                    if clean_word:
                        lyric_set.add(clean_word)

            lyric_dict[name] = list(lyric_set)

    print('{} sets of lyrics found for {} files.'.format(len(lyric_dict), len(files)))
    generate_csv(lyric_dict, 'lyrics.csv')

def search_for_lyric(lyric):
    """Searches lyrics.csv for songs containing lyric."""
    lyric_dict = read_csv('lyrics.csv')
    for song in lyric_dict:
        if lyric in lyric_dict[song]:
            print(song)

if __name__ == '__main__':
    # make_lyric_file('test files')
    search_for_lyric('fo')
